///////////////////////////////////////////////////////////
//  Contact.cs
//  Implementation of the Class Contact
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:42:24
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Contact {

	private string email;
	private string name;
	private string url;

	public Contact(){

	}

	~Contact(){

	}

}//end Contact