///////////////////////////////////////////////////////////
//  Definition.cs
//  Implementation of the Class Definition
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:48:57
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Definition {

	private string name;
	private Schema schema;
	public Schema m_Schema;

	public Definition(){

	}

	~Definition(){

	}

}//end Definition