///////////////////////////////////////////////////////////
//  ExternalDoc.cs
//  Implementation of the Class ExternalDoc
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:49:06
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ExternalDoc {

	private string description;
	private string url;

	public ExternalDoc(){

	}

	~ExternalDoc(){

	}

}//end ExternalDoc