///////////////////////////////////////////////////////////
//  Info.cs
//  Implementation of the Class Info
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:42:11
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Info {

	private Contact contact;
	private string description;
	private License license;
	private string termsOfService;
	private string title;
	private string version;
	public Contact m_Contact;
	public License m_License;

	public Info(){

	}

	~Info(){

	}

}//end Info