///////////////////////////////////////////////////////////
//  License.cs
//  Implementation of the Class License
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:42:34
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class License {

	private string name;
	private string url;

	public License(){

	}

	~License(){

	}

}//end License