///////////////////////////////////////////////////////////
//  Property.cs
//  Implementation of the Class Property
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:49:27
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Property {

	private string name;
	private PropertySchema schema;
	public PropertySchema m_PropertySchema;

	public Property(){

	}

	~Property(){

	}

}//end Property