///////////////////////////////////////////////////////////
//  ResponseCode.cs
//  Implementation of the Class ResponseCode
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:43:27
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ResponseCode {

	private string code;
	public Response m_Response;

	public ResponseCode(){

	}

	~ResponseCode(){

	}

}//end ResponseCode