///////////////////////////////////////////////////////////
//  Response.cs
//  Implementation of the Class Response
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:43:34
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Response {

	private string description;
	private Schema schema;
	public Schema m_Schema;

	public Response(){

	}

	~Response(){

	}

}//end Response