///////////////////////////////////////////////////////////
//  Scope.cs
//  Implementation of the Class Scope
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:48:46
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Scope {

	/// <summary>
	/// write:pets: "modify pets in your account"
	/// </summary>
	private string name;

	public Scope(){

	}

	~Scope(){

	}

}//end Scope