///////////////////////////////////////////////////////////
//  SecurityRequirement.cs
//  Implementation of the Class SecurityRequirement
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:55:55
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SecurityRequirement {

	private List<string> list;
	private string name;

	public SecurityRequirement(){

	}

}//end SecurityRequirement