///////////////////////////////////////////////////////////
//  SecurityDefinition.cs
//  Implementation of the Class SecurityDefinition
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:48:29
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SecurityDefinition {

	private string name;
	private SecurityScheme securityScheme;
	public SecurityScheme m_SecurityScheme;

	public SecurityDefinition(){

	}

	~SecurityDefinition(){

	}

}//end SecurityDefinition