///////////////////////////////////////////////////////////
//  Tag.cs
//  Implementation of the Class Tag
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:42:43
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Tag {

	private string description;
	private string name;

	public Tag(){

	}

	~Tag(){

	}

}//end Tag