///////////////////////////////////////////////////////////
//  XML.cs
//  Implementation of the Class XML
//  Generated by Enterprise Architect
//  Created on:      20-jul-2018 18:49:20
//  Original author: t$0melst
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class XML {

	private string name;

	public XML(){

	}

	~XML(){

	}

}//end XML